// GENERATED by scripts/generate-schema-manifest.mjs. Do not edit by hand.
//
// The columns a database is supposed to have once the base schema and every migration have run.
// Checked against the live database at startup, because a column that exists only in the source is
// a write that fails on an install nobody rebuilt: the base-schema block is itself a migration
// under one fixed id, so adding a column there alone reaches a fresh install and nothing else.
export const DECLARED_SCHEMA: Record<string, string[]> = {
  asset_collection_items: ["asset_id", "collection_id", "position"],
  asset_collections: ["color", "created_at", "description", "id", "name", "updated_at"],
  asset_retention_marks: ["asset_id", "orphan_first_seen_at"],
  assets: ["cache_error", "cache_path", "cache_status", "cache_updated_at", "category_name", "chapters_json", "chapters_probe_status", "chapters_probed_at", "created_at", "duration_seconds", "external_id", "fallback_priority", "folder_path", "hashtags_json", "id", "include_in_programming", "is_global_fallback", "path", "platform_notes", "published_at", "source_id", "status", "tags_json", "title", "title_prefix", "updated_at"],
  audit_events: ["created_at", "id", "message", "type"],
  chat_game_runtime: ["game_id", "settings", "settings_key", "singleton_id", "state", "updated_at"],
  chat_game_settings: ["emote_down", "emote_left", "emote_right", "emote_up", "game_id", "grid_height", "grid_width", "singleton_id", "updated_at"],
  chat_interaction_settings: ["enabled", "request_command", "request_cooldown_seconds", "request_queue_limit", "requests_enabled", "singleton_id", "skip_command", "skip_enabled", "skip_minimum_votes", "skip_threshold_ratio", "skip_window_seconds", "updated_at", "vote_duration_seconds", "vote_minimum_voters", "vote_option_count", "voting_enabled"],
  chat_overlay_messages: ["enabled", "max_messages", "messages", "position", "singleton_id", "updated_at"],
  chat_skip_vote: ["asset_id", "expires_at", "singleton_id", "skip_command", "started_at", "updated_at", "votes", "votes_needed"],
  chat_viewer_requests: ["actor", "asset_id", "created_at", "id", "status"],
  chat_vote_session: ["ballots", "closes_at", "id", "opened_at", "options", "singleton_id", "status", "updated_at", "winner_asset_id"],
  engagement_events: ["actor", "created_at", "id", "kind", "message"],
  engagement_game_runtime: ["active_chatter_count", "mode", "mode_changed_at", "singleton_id", "updated_at"],
  engagement_settings: ["alert_position", "alerts_enabled", "channel_points_enabled", "chat_enabled", "chat_mode", "chat_position", "crowd_mode_enabled", "donations_enabled", "game_enabled", "game_window_minutes", "max_messages", "rate_limit_per_minute", "singleton_id", "small_group_mode_enabled", "solo_mode_enabled", "style", "updated_at"],
  incidents: ["acknowledged_at", "acknowledged_by", "created_at", "fingerprint", "id", "message", "resolved_at", "scope", "severity", "status", "title", "updated_at"],
  managed_config: ["encrypted_payload", "singleton_id", "updated_at"],
  managed_secrets: ["created_at", "encrypted_value", "id"],
  moderation_settings: ["command", "default_minutes", "enabled", "fallback_emote_only", "max_minutes", "min_minutes", "require_prefix", "singleton_id"],
  output_settings: ["fps", "height", "profile_id", "singleton_id", "updated_at", "width"],
  overlay_drafts: ["accent_color", "active_scene_id", "based_on_updated_at", "brand_badge", "channel_name", "custom_layers_json", "disabled_layers_json", "emergency_banner", "enabled", "headline", "insert_headline", "insert_scene_preset", "layer_order_json", "panel_anchor", "panel_placements_json", "queue_preview_count", "reconnect_headline", "reconnect_scene_preset", "replay_label", "scene_preset", "scenes_json", "show_clock", "show_current_category", "show_next_item", "show_queue_preview", "show_schedule_teaser", "show_source_label", "singleton_id", "standby_headline", "standby_scene_preset", "surface_style", "ticker_rotate_seconds", "ticker_text", "title_scale", "typography_preset", "updated_at"],
  overlay_scene_presets: ["created_at", "description", "id", "name", "overlay_json", "updated_at"],
  overlay_settings: ["accent_color", "active_scene_id", "brand_badge", "channel_name", "custom_layers_json", "disabled_layers_json", "emergency_banner", "enabled", "headline", "insert_headline", "insert_scene_preset", "layer_order_json", "panel_anchor", "panel_placements_json", "queue_preview_count", "reconnect_headline", "reconnect_scene_preset", "replay_label", "scene_preset", "scenes_json", "show_clock", "show_current_category", "show_next_item", "show_queue_preview", "show_schedule_teaser", "show_source_label", "singleton_id", "standby_headline", "standby_scene_preset", "surface_style", "ticker_rotate_seconds", "ticker_text", "title_scale", "typography_preset", "updated_at"],
  overlay_video_sources: ["encrypted_publish_key", "encrypted_url", "id", "ingest_kind", "live_retry_at", "live_state", "live_state_at", "name", "updated_at", "url_present"],
  playout_runtime: ["crash_count_window", "crash_loop_detected", "cuepoint_fired_keys", "cuepoint_last_asset_id", "cuepoint_last_triggered_at", "cuepoint_window_key", "current_asset_id", "current_destination_id", "current_title", "desired_asset_id", "fallback_tier", "heartbeat_at", "insert_asset_id", "insert_requested_at", "insert_status", "last_error", "last_exit_code", "last_stderr_sample", "last_successful_asset_id", "last_successful_start_at", "last_transition_at", "live_bridge_input_type", "live_bridge_input_url", "live_bridge_label", "live_bridge_last_error", "live_bridge_released_at", "live_bridge_requested_at", "live_bridge_started_at", "live_bridge_status", "manual_next_asset_id", "manual_next_requested_at", "message", "next_asset_id", "next_title", "override_asset_id", "override_mode", "override_until", "pending_action", "pending_action_requested_at", "prefetch_error", "prefetch_status", "prefetched_asset_id", "prefetched_at", "prefetched_title", "previous_asset_id", "previous_title", "process_pid", "process_started_at", "program_feed_buffered_seconds", "program_feed_playlist_path", "program_feed_status", "program_feed_target_seconds", "program_feed_updated_at", "queue_items", "queue_version", "queued_asset_ids", "restart_count", "restart_requested_at", "selection_reason_code", "singleton_id", "skip_asset_id", "skip_until", "status", "transition_ready_at", "transition_state", "transition_target_asset_id", "transition_target_kind", "transition_target_title", "uplink_destination_ids", "uplink_heartbeat_at", "uplink_input_mode", "uplink_last_exit_code", "uplink_last_exit_planned", "uplink_last_exit_reason", "uplink_reconnect_until", "uplink_restart_count", "uplink_started_at", "uplink_status", "uplink_unplanned_restart_count", "worker_heartbeat_at"],
  pools: ["audio_lane_asset_id", "audio_lane_volume_percent", "cursor_asset_id", "id", "insert_asset_id", "insert_every_items", "items_since_insert", "name", "playback_mode", "source_ids", "updated_at"],
  presence_windows: ["actor", "applied_minutes", "clamp_reason", "created_at", "expires_at", "id", "minutes", "requested_minutes"],
  schedule_blocks: ["category_name", "cuepoint_asset_id", "cuepoint_offsets_seconds", "day_of_week", "duration_minutes", "id", "pool_id", "repeat_group_id", "repeat_mode", "show_id", "source_name", "start_hour", "start_minute_of_day", "title"],
  schema_migrations: ["applied_at", "description", "id"],
  show_profiles: ["category_name", "color", "default_duration_minutes", "description", "id", "name", "updated_at"],
  source_sync_runs: ["discovered_assets", "error_message", "finished_at", "id", "ready_assets", "source_id", "started_at", "status", "summary"],
  sources: ["connector_kind", "enabled", "external_url", "id", "last_synced_at", "name", "notes", "status", "type"],
  stream_destinations: ["enabled", "encrypted_stream_key", "failure_count", "id", "last_error", "last_failure_at", "last_validated_at", "name", "notes", "output_profile_id", "priority", "provider", "role", "rtmp_url", "status", "stream_key_present"],
  system_state: ["initialized", "owner_created_at", "owner_email", "owner_password_hash", "singleton_id"],
  team_access_grants: ["created_at", "created_by", "id", "role", "twitch_login"],
  twitch_broadcaster_connection: ["access_token", "broadcaster_id", "broadcaster_login", "connected_at", "error", "last_refresh_at", "refresh_token", "singleton_id", "status", "token_expires_at"],
  twitch_connection: ["access_token", "broadcaster_id", "broadcaster_login", "connected_at", "error", "last_metadata_sync_at", "last_refresh_at", "last_schedule_sync_at", "last_synced_category_id", "last_synced_category_name", "last_synced_title", "live_status", "refresh_token", "singleton_id", "started_at", "status", "token_expires_at", "viewer_count"],
  twitch_schedule_segments: ["block_id", "key", "segment_id", "start_time", "synced_at", "title"],
  users: ["auth_provider", "created_at", "display_name", "email", "id", "last_login_at", "password_hash", "role", "twitch_login", "twitch_user_id", "two_factor_confirmed_at", "two_factor_enabled", "two_factor_secret"]
};
